### ISSUE TITLE
Highlighting citation keys

### ISSUE THREAD

**Issue by daijiang** [batpigandme/night-owlish#1]
Thanks for the awesome theme! I just tried it and I love it! There are a couple of things that I wonder can you improve it?

To see this, create a new RMarkdown file within RStudio, then add the following sentence in the body.

```
This is an R Markdown document [@citation]. And (_italic with blank within parathese immediately_).
( _italic with blank within parathese with heading space_).
```

![image](https://user-images.githubusercontent.com/1696911/47370634-2b142d00-d6b4-11e8-8968-09db23c16373.png)

Can you change the color of the citation key? Also, the italic within parenthesis without a heading space does not work.

Thanks!

**Comment by batpigandme** [comment]
Alas, I'm limited to the scopes that already exist in the built-in themes. I typically test against Tomorrow Night Bright (see screenshot of the above, below), but if there _is_ a built-in theme that differentiates the above syntax, let me know which one, and I can look into it when time allows.
![image](https://user-images.githubusercontent.com/831732/47371566-0e78f480-d6b6-11e8-9ee9-7b9435d29c9e.png)

I looked at a few others (e.g. Solarized Dark, below) and didn't happen to see any that worked with this, but I didn't go through them all.
![image](https://user-images.githubusercontent.com/831732/47371718-4aac5500-d6b6-11e8-8c37-fba4adf0c9fa.png)

**Comment by daijiang** [comment]
Thanks. For the citation key, I think the default one (teammate), Chrome, and Twilight work. But none for the italic one...

**Comment by batpigandme** [comment]
Interesting. Yeah, so unless the scope is added for italics, that one won't happen (sorry). With Chrome at least, the citation has the list class (`.ace_list`) style applied to it, but I'll have to dig deeper to see if it has different selectors build in as well.

**Comment by daijiang** [comment]
Thanks!!

**Comment by batpigandme** [comment]
💥 scope added!
![citation key highlight](https://user-images.githubusercontent.com/831732/47781361-e56aec00-dcd3-11e8-9b98-117cd091a782.png)

**Comment by daijiang** [comment]
Awesome! Thanks!
