### ISSUE TITLE
Theme will not import in Rstudio Daily Build

### ISSUE THREAD

**Issue by renekyewski** [batpigandme/night-owlish#2]
Hi there, I get a error when I try to add your theme:

![image](https://user-images.githubusercontent.com/45432910/54431760-8ad4a880-4727-11e9-8c73-ded63a8bd155.png)

In the console I get:
Error in regexpr(pattern, text, ignore.case = ignore.case, useBytes = useBytes,  : 
  invalid input '

Using RStduio 1.2.1327 on Windows 10.

Thanks

**Comment by batpigandme** [comment]
Hi @renekyewski,

Have you tried installing any other RStudio themes? There are some in the repos at this link:
https://github.com/topics/rstudio-theme

You could download any of the `.tmTheme`s here and see if they import for you: https://tmtheme-editor.herokuapp.com/#!/editor/theme/Atom%20Dark

I haven't changed anything in quite some time, so it might be an IDE issue, and not one I can fix on my end. (@MariaSemple – do you have any hints?)

**Comment by batpigandme** [comment]
You can also try importing the `tmtheme` file instead.

FWIW, I _was_ able to import a different `.rstheme` file in the latest [Preview build](https://www.rstudio.com/products/rstudio/download/preview/).

**Comment by renekyewski** [comment]
That was a fast reply :) 

The Atom Theme with the link you sent me imported fine. Yours also does not work as the tmtheme file. This time giving me a different error:

![image](https://user-images.githubusercontent.com/45432910/54433524-57e0e380-472c-11e9-9f91-c11132135811.png)

**Comment by batpigandme** [comment]
Hmm… It's possible it's an encoding error (I'm on a Mac – don't have Windows to test). I just made a duplicate and imported it which worked fine (I'm using 1.2.1326, not .1327, but it would surprise me if that's the difference). 
Here's the dummy theme:
https://gist.github.com/batpigandme/d84e1535f31c848f5902d4f0cfd9839b

What happens if you copy the text, and paste it into a file in a text editor? (Just save as `<whateveryouwant>.rstheme`).

**Comment by batpigandme** [comment]
Hmm, and that's a different error with the `.tmtheme` — I have no clue what `Specification mandate value for attribute data-pjax-transient [41]` means, but maybe that'll be a clue. 🤔

**Comment by renekyewski** [comment]
Manually pasting it and creating a new file did the job. Thanks for your help.

**Comment by batpigandme** [comment]
Awesome! I have zero clue why, but I'm glad it worked! 🎉
