### ISSUE TITLE
Adding color for .ace_invisible

### ISSUE THREAD

**Issue by hlynurhallgrims** [batpigandme/night-owlish#7]
The whitespace characters default to a rather "in your face" color value. 

For those who use the optional whitespace characters, this is what it looks like in the current theme.

![image](https://user-images.githubusercontent.com/6782760/69836500-20c24c00-1241-11ea-8afa-7c5d9bcbbc9f.png)

Adding this: (see: https://github.com/batpigandme/night-owlish/pull/6)
```
.ace_invisible {
	color: rgba(135, 156, 173, 0.4);
}  
```
Gives this look.

![image](https://user-images.githubusercontent.com/6782760/69836528-6252f700-1241-11ea-9be3-36d58381edc4.png)

Just a thought 😃

**Comment by batpigandme** [comment]
Oh, sweet! Looks way better. Thanks for this.

**Comment by batpigandme** [comment]
Fixed by #6
