### ISSUE TITLE
Port Bash syntax highlighting to Zsh (in R Markdown chunks)

### ISSUE THREAD

**Issue by leowill01** [batpigandme/night-owlish#8]
Title is self explanatory.

I would like the Zsh syntax highlighting in R Markdown chunks: 

![image](https://user-images.githubusercontent.com/43548130/72549911-39b9a780-3857-11ea-9518-196eb793c697.png)

to have better coloring like a Bash chunk does:

![image](https://user-images.githubusercontent.com/43548130/72549950-4e963b00-3857-11ea-93f4-ad19d7f4279e.png)

**Comment by batpigandme** [comment]
Do you have an example of a theme that does syntax highlighting for bash and zsh chunks? Honestly, I kinda just reverse engineer things! 😉

**Comment by leowill01** [comment]
Hey - your theme already does this (both of the previous screenshots are from your Night Owl RStudio theme), but what I'm looking for is to make the Zsh colors the *same* as the Bash colors. Is that doable?

**Comment by batpigandme** [comment]
I'm not sure! That's why I was asking if there was another rstudio theme that has scopes/highlighting that work well for zsh. When I've got some more time (read: after rstudio::conf), I'll poke around and see what I can find using Inspect Element.

**Comment by batpigandme** [comment]
OK, to confirm. This is an issue with the scopes/tokenization, which comes from the editor, not the theme. 

In the `zsh` chunk, `$i` doesn't get the `.ace_variable` scope (the whole thing is interpreted as a string, which is how you get the syntax highlighting in the bash chunk (see images below)

**bash**
<img width="1266" alt="syntax highlighting for bash chunk" src="https://user-images.githubusercontent.com/831732/72980377-7d0c9c80-3da8-11ea-8913-eace1b8403c3.png">
**zsh**
<img width="1031" alt="syntax highlighting for zsh chunk" src="https://user-images.githubusercontent.com/831732/72980418-8bf34f00-3da8-11ea-9737-babdaa029e9c.png">

Sorry I can't be of more help! FWIW, if it's tokenized correctly, the theme _will_ apply the right color scheme.
